services:
  # =====================
  # API Gateway (Kong)
  # =====================
  kong:
    image: kong:3.4
    container_name: hospital-app-kong
    restart: unless-stopped
    depends_on:
      - user-service
      - appointment-service
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: ${KONG_DECLARATIVE_CONFIG}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  # =====================
  # User Service
  # =====================
  user-service:
    build:
      context: ./
      dockerfile: user_service/Dockerfile
    container_name: hospital-app-user-service
    depends_on:
      user-service-db:
        condition: service_healthy
    ports:
      - "8081:8080"
      - "5005:5005"
      - "9090:9090"
    environment:
      ENABLE_REMOTE_DEBUG: ${ENABLE_REMOTE_DEBUG}
      HOSPITAL_APP_USER_SERVICE_DB_URL: ${USER_SERVICE_DB_URL}
      HOSPITAL_APP_USER_SERVICE_DB_USER: ${USER_SERVICE_DB_USER}
      HOSPITAL_APP_USER_SERVICE_DB_PASS: ${USER_SERVICE_DB_PASS}
      HOSPITAL_APP_USER_SERVICE_DB_DRIVER: ${USER_SERVICE_DB_DRIVER}
      HOSPITAL_APP_USER_SERVICE_DB_DDL_AUTO: ${USER_SERVICE_DB_DDL_AUTO}
      HOSPITAL_APP_USER_SERVICE_DB_DIALECT: ${USER_SERVICE_DB_DIALECT}

      # GRPC Certifications
      HOSPITAL_APP_USER_SERVICE_CRT: ${USER_SERVICE_CRT}
      HOSPITAL_APP_USER_SERVICE_KEY: ${USER_SERVICE_KEY}
      HOSPITAL_APP_USER_SERVICE_CA: ${USER_SERVICE_CA}
      HOSPITAL_APP_USER_SERVICE_CLIENT_AUTH: ${USER_SERVICE_CLIENT_AUTH}

    volumes:
      - m2-repo:/root/.m2

  user-service-db:
    image: postgres:15-alpine3.21
    container_name: hospital-app-user-service-db
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB}
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASS}
    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_DB_USER} -d ${USER_SERVICE_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5437:5432"

  # =====================
  # Appointment Service
  # =====================
  appointment-service:
    build:
      context: ./
      dockerfile: appointment_service/Dockerfile
    container_name: hospital-app-appointment-service
    depends_on:
      appointment-service-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8080"
      - "5006:5005"
    environment:
      ENABLE_REMOTE_DEBUG: ${ENABLE_REMOTE_DEBUG}
      HOSPITAL_APP_APPOINTMENT_SERVICE_DB_URL: ${APPOINTMENT_SERVICE_DB_URL}
      HOSPITAL_APP_APPOINTMENT_SERVICE_DB_USER: ${APPOINTMENT_SERVICE_DB_USER}
      HOSPITAL_APP_APPOINTMENT_SERVICE_DB_PASS: ${APPOINTMENT_SERVICE_DB_PASS}
      HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DRIVER: ${APPOINTMENT_SERVICE_DB_DRIVER}
      HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DDL_AUTO: ${APPOINTMENT_SERVICE_DB_DDL_AUTO}
      HOSPITAL_APP_APPOINTMENT_SERVICE_DB_DIALECT: ${APPOINTMENT_SERVICE_DB_DIALECT}
      HOSPITAL_APP_RABBITMQ_HOST: rabbitmq
      HOSPITAL_APP_RABBITMQ_PORT: 5671
      HOSPITAL_APP_RABBITMQ_USER: guest
      HOSPITAL_APP_RABBITMQ_PASS: guest
      HOSPITAL_APP_RABBITMQ_SSL_ENABLED: true
      HOSPITAL_APP_RABBITMQ_SSL_ALGO: TLSv1.2
      HOSPITAL_APP_RABBITMQ_SSL_VALIDATE: true
      HOSPITAL_APP_RABBITMQ_KEYSTORE: classpath:rabbitmq/client_keystore.p12
      HOSPITAL_APP_RABBITMQ_KEYSTORE_PASS: changeit
      HOSPITAL_APP_RABBITMQ_TRUSTSTORE: classpath:rabbitmq/truststore.p12
      HOSPITAL_APP_RABBITMQ_TRUSTSTORE_PASS: changeit
      HOSPITAL_APP_USER_SERVICE_URL: http://user-service:8080
      HOSPITAL_APP_APPOINTMENT_SERVICE_CRT: classpath:tls/appointment_service.crt
      HOSPITAL_APP_APPOINTMENT_SERVICE_KEY: classpath:tls/appointment_service_pkcs8.key
      HOSPITAL_APP_APPOINTMENT_SERVICE_CA: classpath:tls/ca.crt
    volumes:
      - m2-repo:/root/.m2

  appointment-service-db:
    image: postgres:15-alpine3.21
    container_name: hospital-app-appointment-service-db
    environment:
      POSTGRES_DB: ${APPOINTMENT_SERVICE_DB}
      POSTGRES_USER: ${APPOINTMENT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${APPOINTMENT_SERVICE_DB_PASS}
    volumes:
      - appointment-service-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APPOINTMENT_SERVICE_DB_USER} -d ${APPOINTMENT_SERVICE_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5435:5432"

  # =====================
  # Notification Service
  # =====================
  notification-service:
    build:
      context: ./
      dockerfile: notification_service/Dockerfile
    container_name: hospital-app-notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8083:8080"
      - "5009:5005"
    environment:
      ENABLE_REMOTE_DEBUG: ${ENABLE_REMOTE_DEBUG}
      HOSPITAL_APP_NOTIFICATION_SERVICE_DB_URL: ${NOTIFICATION_SERVICE_DB_URL}
      HOSPITAL_APP_NOTIFICATION_SERVICE_DB_USER: ${NOTIFICATION_SERVICE_DB_USER}
      HOSPITAL_APP_NOTIFICATION_SERVICE_DB_PASS: ${NOTIFICATION_SERVICE_DB_PASS}
      HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DRIVER: ${NOTIFICATION_SERVICE_DB_DRIVER}
      HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DDL_AUTO: ${NOTIFICATION_SERVICE_DB_DDL_AUTO}
      HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DIALECT: ${NOTIFICATION_SERVICE_DB_DIALECT}
    volumes:
      - m2-repo:/root/.m2

  notification-service-db:
    image: postgres:15-alpine3.21
    container_name: hospital-app-notification-service-db
    environment:
      POSTGRES_DB: ${NOTIFICATION_SERVICE_DB}
      POSTGRES_USER: ${NOTIFICATION_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_SERVICE_DB_PASS}
    volumes:
      - notification-service-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NOTIFICATION_SERVICE_DB_USER} -d ${NOTIFICATION_SERVICE_DB} -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5438:5432"

  # =====================
  # Appointment History Service
  # =====================
  appointment-history-service:
    build:
      context: ./
      dockerfile: appointment_history_service/Dockerfile
    container_name: hospital-app-appointment-history-service
    depends_on:
      appointment-service-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8084:8080"
      - "5008:5005"
    environment:
      ENABLE_REMOTE_DEBUG: ${ENABLE_REMOTE_DEBUG}
      HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_URL: ${APPOINTMENT_HISTORY_SERVICE_DB_URL}
      HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_USER: ${APPOINTMENT_HISTORY_SERVICE_DB_USER}
      HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_PASS: ${APPOINTMENT_HISTORY_SERVICE_DB_PASS}
      HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_DRIVER: ${APPOINTMENT_HISTORY_SERVICE_DB_DRIVER}
      HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_DDL_AUTO: ${APPOINTMENT_HISTORY_SERVICE_DB_DDL_AUTO}
      HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_DIALECT: ${APPOINTMENT_HISTORY_SERVICE_DB_DIALECT}
      HOSPITAL_APP_RABBITMQ_HOST: rabbitmq
      HOSPITAL_APP_RABBITMQ_PORT: 5671
      HOSPITAL_APP_RABBITMQ_USER: guest
      HOSPITAL_APP_RABBITMQ_PASS: guest
      HOSPITAL_APP_RABBITMQ_SSL_ENABLED: true
      HOSPITAL_APP_RABBITMQ_SSL_ALGO: TLSv1.2
      HOSPITAL_APP_RABBITMQ_SSL_VALIDATE: true
      HOSPITAL_APP_RABBITMQ_KEYSTORE: classpath:rabbitmq/client_keystore.p12
      HOSPITAL_APP_RABBITMQ_KEYSTORE_PASS: changeit
      HOSPITAL_APP_RABBITMQ_TRUSTSTORE: classpath:rabbitmq/truststore.p12
      HOSPITAL_APP_RABBITMQ_TRUSTSTORE_PASS: changeit
    volumes:
      - m2-repo:/root/.m2

  appointment-history-service-db:
    image: postgres:15-alpine3.21
    container_name: hospital-app-appointment-history-service-db
    environment:
      POSTGRES_DB: ${APPOINTMENT_HISTORY_SERVICE_DB}
      POSTGRES_USER: ${APPOINTMENT_HISTORY_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${APPOINTMENT_HISTORY_SERVICE_DB_PASS}
    volumes:
      - appointment--history-service-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APPOINTMENT_HISTORY_SERVICE_DB_USER} -d ${APPOINTMENT_HISTORY_SERVICE_DB} -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5436:5432"

  # =====================
  # RabbitMQ
  # =====================
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: hospital-app-rabbitmq
    ports:
      - "5671:5671" # SSL
      - "15671:15671" # Management over HTTPS
    volumes:
      - ./rabbitmq/certs:/etc/rabbitmq/certs:ro
      - ./rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

# =====================
# Volumes
# =====================
volumes:
  m2-repo:
  user-service-postgres-data:
  appointment-service-postgres-data:
  appointment--history-service-postgres-data:
  notification-service-postgres-data:

# =====================
# Networks
# =====================
networks:
  hospital-net:
    driver: bridge
